                ifndef _HMM2_HISCORES_
                define _HMM2_HISCORES_
; ============================================================================
; ASM High Scores screen.
; Assets live in RAM_G[0] from HMM2HISC.PAK. Metadata lives in page #A5 @ #C000
; and is generated by hiscores_pack.py into generated_hiscores_meta.inc.
; ============================================================================

                include "generated_hiscores.inc"
                include "generated_hiscores_meta.inc"

HS_ENTRY_COUNT  EQU 10
HS_ROW_Y        EQU 72
HS_ROW_STEP     EQU 40
HS_COL_PLAYER   EQU 88
HS_COL_SCENARIO EQU 244
HS_COL_DAYS     EQU 403
HS_COL_RATING   EQU 484
HS_MONSTER_X    EQU 554
HS_MONSTER_Y    EQU 91

HS_BUTTON_OTHER_X EQU 8
HS_BUTTON_EXIT_X  EQU 604
HS_BUTTON_Y       EQU 315
HS_BUTTON_W       EQU 28
HS_BUTTON_H       EQU 136

HiScores_EnterStandard:
                CALL Render_BlackFrame
                CALL HiScores_LoadFromPak
                XOR  A
                LD   (HsIsCampaign), A
                LD   (HsPressedOther), A
                LD   (HsPressedExit), A
                LD   (HsLmbLatch), A
                LD   (HsAnimationFrame), A
                LD   A, GAME_MODE_HIGHSCORES_STANDARD
                LD   (GameMode), A
                RET

HiScores_EnterCampaign:
                CALL Render_BlackFrame
                CALL HiScores_LoadFromPak
                LD   A, 1
                LD   (HsIsCampaign), A
                XOR  A
                LD   (HsPressedOther), A
                LD   (HsPressedExit), A
                LD   (HsLmbLatch), A
                LD   (HsAnimationFrame), A
                LD   A, GAME_MODE_HIGHSCORES_CAMPAIGN
                LD   (GameMode), A
                RET

HiScores_Update:
                CALL Music_Tick_Tramp

                CALL Input_Esc
                JR   NZ, .exit_to_menu

                CALL Input_MouseX
                LD   (HsInputX), HL
                CALL Input_MouseY
                LD   (HsInputY), HL

                CALL Input_MouseLMB
                JR   NZ, .pressed
.released:     XOR  A
                LD   (HsPressedOther), A
                LD   (HsPressedExit), A
                LD   (HsLmbLatch), A
                RET

.pressed:       CALL HsPointInOtherButton
                LD   (HsPressedOther), A
                CALL HsPointInExitButton
                LD   (HsPressedExit), A
                LD   A, (HsLmbLatch)
                OR   A
                JR   NZ, .stay                ; уже зажато (дебаунс) → остаться
                LD   A, 1
                LD   (HsLmbLatch), A
                LD   A, (HsPressedExit)
                OR   A
                JR   NZ, .exit_to_menu
                LD   A, (HsPressedOther)
                OR   A
                JR   Z, .stay                 ; не «Other» → остаться
                LD   A, (HsIsCampaign)
                XOR  1
                LD   (HsIsCampaign), A
                OR   A
                JR   Z, .standard
                LD   A, GAME_MODE_HIGHSCORES_CAMPAIGN
                LD   (GameMode), A
                JR   .stay                    ; вид переключён → остаться
.standard:      LD   A, GAME_MODE_HIGHSCORES_STANDARD
                LD   (GameMode), A
.stay:          XOR  A                        ; A=0 → действие «остаться»
                RET

; Выход в меню: НЕ зовём Render_BlackFrame/Menu_Enter из оверлея (slot3-edge —
; Menu_Enter теперь в #A7). Возвращаем код A=1; резидентный HiScores_Update_Tramp
; сделает чёрный кадр + Menu_Enter_Tramp (маппит #A7).
.exit_to_menu:
                LD   A, 1
                RET

Render_HiScores:
                LD   A, (HsAnimationFrame)
                INC  A
                LD   (HsAnimationFrame), A

                CALL Hsc_RenderBegin
                CALL Hsc_SetOpaquePalette
                LD   HL, HsBgTable
                LD   B, HsBgTable_COUNT
                CALL Hsc_RenderSpriteTable
                CALL Hsc_SetTransparentPalette

                LD   A, (HsIsCampaign)
                OR   A
                JR   Z, .titleStandard
                LD   HL, HsTitleCampaignTable
                LD   B, HsTitleCampaignTable_COUNT
                JR   .title
.titleStandard: LD   HL, HsTitleStandardTable
                LD   B, HsTitleStandardTable_COUNT
.title:         CALL Hsc_RenderSpriteTable

                CALL Hsc_RenderRows
                CALL Hsc_RenderButtons
                JP   Hsc_RenderEnd

; --- Load HMM2HISC.PAK into RAM_G[0] -----------------------------------------
HiScores_LoadFromPak:
                LD   HL, HiScoresPakName
                LD   DE, MenuNameBuf
                LD   BC, 13
                LDIR
                CALL Loader_Init
                CALL Loader_Mount
                RET  NC
                LD   HL, MenuNameBuf
                CALL Loader_OpenFile
                RET  NC
                LD   C, RAWPAK_BUF_PAGE
                LD   HL, 0
                LD   B, HISCORES_BODY_SECTOR
                CALL Loader_ReadSectors
                LD   BC, HISCORES_PAYLOAD_SECTORS
                CALL Loader_StreamToRamG
                RET

; --- Input hit tests ----------------------------------------------------------
HsPointInOtherButton:
                LD   DE, HS_BUTTON_OTHER_X
                LD   HL, (HsInputX)
                CALL HsCmpHLDE
                JR   C, .no
                LD   DE, HS_BUTTON_OTHER_X + HS_BUTTON_W
                LD   HL, (HsInputX)
                CALL HsCmpHLDE
                JR   NC, .no
                JR   HsPointInButtonY
.no:            XOR  A
                RET

HsPointInExitButton:
                LD   DE, HS_BUTTON_EXIT_X
                LD   HL, (HsInputX)
                CALL HsCmpHLDE
                JR   C, .no
                LD   DE, HS_BUTTON_EXIT_X + HS_BUTTON_W
                LD   HL, (HsInputX)
                CALL HsCmpHLDE
                JR   NC, .no
                JR   HsPointInButtonY
.no:            XOR  A
                RET

HsPointInButtonY:
                LD   DE, HS_BUTTON_Y
                LD   HL, (HsInputY)
                CALL HsCmpHLDE
                JR   C, .no
                LD   DE, HS_BUTTON_Y + HS_BUTTON_H
                LD   HL, (HsInputY)
                CALL HsCmpHLDE
                JR   NC, .no
                LD   A, 1
                RET
.no:            XOR  A
                RET

; Carry set when HL < DE.
HsCmpHLDE:
                OR   A
                SBC  HL, DE
                RET

; --- Frame builder ------------------------------------------------------------
Hsc_RenderBegin:
                LD   HL, 0
                LD   (HscDlRamLo), HL
                LD   HL, CMD_ADDRESS_PTR
                LD   (FT.Coprocessor.BufferPtr), HL
                LD   HL, HscFrameBegin_DL
                LD   BC, HscFrameBegin_DL_SIZE
                JP   Render_CmdBufCopy

Hsc_RenderEnd:
                CALL Hsc_CmdFlushIfNear
                LD   HL, HscFrameEnd_DL
                LD   BC, HscFrameEnd_DL_SIZE
                CALL Render_CmdBufCopy
                CALL Render_GlobalCursor
                CALL Hsc_DlFlush
                CALL Render_BeginFrameSync
                FT_WR_REG8 FT_REG_DLSWAP, FT_DLSWAP_FRAME
                RET

Hsc_SetOpaquePalette:
                LD   DE, HS_OPAQUE_PAL_LO
                LD   A, HS_OPAQUE_PAL_HI
                JR   Hsc_SetPalette

Hsc_SetTransparentPalette:
                LD   DE, HS_TRANSPARENT_PAL_LO
                LD   A, HS_TRANSPARENT_PAL_HI

Hsc_SetPalette:
                AND  #3F
                LD   H, #2A
                LD   L, A
                JP   Render_CmdBufWrite32

Hsc_SetUpscaleTransform:
                LD   HL, HscUpscaleTransform_DL
                LD   BC, HscBitmapTransform_DL_SIZE
                JP   Render_CmdBufCopy

Hsc_SetNativeTextTransform:
                LD   HL, HscNativeTextTransform_DL
                LD   BC, HscBitmapTransform_DL_SIZE
                JP   Render_CmdBufCopy

Hsc_RenderSpriteTable:
                LD   (HsTablePtr), HL
                LD   A, B
                LD   (HsTableCount), A
.loop:          LD   A, (HsTableCount)
                OR   A
                RET  Z
                LD   HL, (HsTablePtr)
                PUSH HL
                POP  IX
                XOR  A
                LD   (HsBaseX), A
                LD   (HsBaseX + 1), A
                LD   (HsBaseY), A
                LD   (HsBaseY + 1), A
                CALL Hsc_EmitSpriteEntry
                LD   HL, (HsTablePtr)
                LD   DE, HS_SPRITE_ENTRY_SIZE
                ADD  HL, DE
                LD   (HsTablePtr), HL
                LD   A, (HsTableCount)
                DEC  A
                LD   (HsTableCount), A
                JR   .loop

Hsc_RenderRows:
                LD   A, (HsIsCampaign)
                OR   A
                JR   Z, .standard
                LD   HL, HsCampaignRows
                JR   .rows
.standard:      LD   HL, HsStandardRows
.rows:          LD   (HsRowPtr), HL
                LD   HL, HS_ROW_Y
                LD   (HsRowY), HL
                LD   HL, HS_MONSTER_Y
                LD   (HsMonsterY), HL
                LD   A, HS_ENTRY_COUNT
                LD   (HsRowsLeft), A
.loop:          LD   A, (HsRowsLeft)
                OR   A
                RET  Z
                LD   HL, (HsRowPtr)
                PUSH HL
                POP  IX
                LD   L, (IX+0) : LD H, (IX+1) : LD (HsPlayerPtr), HL
                LD   L, (IX+2) : LD H, (IX+3) : LD (HsScenarioPtr), HL
                LD   L, (IX+4) : LD H, (IX+5) : LD (HsDays), HL
                LD   L, (IX+6) : LD H, (IX+7) : LD (HsRating), HL
                LD   L, (IX+8) : LD H, (IX+9) : LD (HsMonster0Ptr), HL
                LD   L, (IX+10): LD H, (IX+11): LD (HsMonster1Ptr), HL

                CALL Hsc_SetNativeTextTransform
                LD   HL, (HsPlayerPtr)
                LD   DE, HS_COL_PLAYER
                LD   BC, (HsRowY)
                CALL Hsc_DrawText
                LD   HL, (HsScenarioPtr)
                LD   DE, HS_COL_SCENARIO
                LD   BC, (HsRowY)
                CALL Hsc_DrawText
                LD   HL, (HsDays)
                CALL Hsc_NumberToText
                LD   HL, HsNumBuf
                LD   DE, HS_COL_DAYS
                LD   BC, (HsRowY)
                CALL Hsc_DrawText
                LD   HL, (HsRating)
                CALL Hsc_NumberToText
                LD   HL, HsNumBuf
                LD   DE, HS_COL_RATING
                LD   BC, (HsRowY)
                CALL Hsc_DrawText

                CALL Hsc_SetUpscaleTransform
                LD   HL, HS_MONSTER_X
                LD   (HsBaseX), HL
                LD   HL, (HsMonsterY)
                LD   (HsBaseY), HL
                LD   HL, (HsMonster0Ptr)
                PUSH HL
                POP  IX
                CALL Hsc_EmitSpriteEntry
                LD   HL, (HsMonster1Ptr)
                PUSH HL
                POP  IX
                CALL Hsc_EmitSpriteEntry

                LD   HL, (HsRowPtr)
                LD   DE, HS_ROW_ENTRY_SIZE
                ADD  HL, DE
                LD   (HsRowPtr), HL
                LD   HL, (HsRowY)
                LD   DE, HS_ROW_STEP
                ADD  HL, DE
                LD   (HsRowY), HL
                LD   HL, (HsMonsterY)
                LD   DE, HS_ROW_STEP
                ADD  HL, DE
                LD   (HsMonsterY), HL
                LD   A, (HsRowsLeft)
                DEC  A
                LD   (HsRowsLeft), A
                JP   .loop

Hsc_RenderButtons:
                XOR  A
                LD   (HsBaseX), A
                LD   (HsBaseX + 1), A
                LD   (HsBaseY), A
                LD   (HsBaseY + 1), A
                LD   A, (HsIsCampaign)
                OR   A
                JR   Z, .standard
                LD   HL, HsButtonCampaignTable
                JR   .other
.standard:      LD   HL, HsButtonStandardTable
.other:         LD   A, (HsPressedOther)
                OR   A
                JR   Z, .otherReady
                LD   DE, HS_SPRITE_ENTRY_SIZE
                ADD  HL, DE
.otherReady:    PUSH HL
                POP  IX
                CALL Hsc_EmitSpriteEntry
                LD   HL, HsButtonExitTable
                LD   A, (HsPressedExit)
                OR   A
                JR   Z, .exitReady
                LD   DE, HS_SPRITE_ENTRY_SIZE
                ADD  HL, DE
.exitReady:     PUSH HL
                POP  IX
                JP   Hsc_EmitSpriteEntry

Hsc_EmitSpriteEntry:
                CALL Hsc_CmdFlushIfNear
                LD   E, (IX+0)
                LD   D, (IX+1)
                LD   A, (IX+2)
                LD   H, #01
                LD   L, A
                CALL Render_CmdBufWrite32

                LD   L, (IX+3)
                LD   H, (IX+4)
                LD   (HsSpriteW), HL
                LD   L, (IX+5)
                LD   H, (IX+6)
                LD   (HsSpriteH), HL
                LD   L, (IX+7)
                LD   H, (IX+8)
                LD   (HsSpriteSizeW), HL
                LD   L, (IX+9)
                LD   H, (IX+10)
                LD   (HsSpriteSizeH), HL

                LD   HL, (HsSpriteW)
                CALL Hsc_WidthShift7ToA
                ADD  A, #78
                LD   L, A
                LD   H, #07
                CALL Hsc_LowWordFromWH
                CALL Render_CmdBufWrite32

                LD   HL, (HsSpriteSizeW)
                CALL Hsc_WidthShift7ToA
                LD   L, A
                LD   H, #08
                CALL Hsc_LowWordFromSizeWH
                CALL Render_CmdBufWrite32

                LD   L, (IX+11)
                LD   H, (IX+12)
                LD   DE, (HsBaseX)
                ADD  HL, DE
                CALL Hsc_ScaleSignedLogical
                LD   (RenderPathVertexX), HL
                LD   L, (IX+13)
                LD   H, (IX+14)
                LD   DE, (HsBaseY)
                ADD  HL, DE
                CALL Hsc_ScaleSignedLogical
                LD   (RenderPathVertexY), HL
                JP   Render_WriteVertex2FCmd

Hsc_ScaleSignedLogical:
                BIT  7, H
                JR   Z, .positive
                LD   HL, 0
                RET
.positive:      JP   Render_ScaleHL_8_5_ToVertex

Hsc_DrawText:
                LD   (HsTextPtr), HL
                LD   H, D
                LD   L, E
                CALL Hsc_ScaleSignedLogical
                LD   (HsPenX), HL
                LD   H, B
                LD   L, C
                CALL Hsc_ScaleSignedLogical
                LD   (HsPenY), HL
                LD   A, 40
                LD   (HsTextLeft), A
.loop:          LD   A, (HsTextLeft)
                OR   A
                RET  Z
                LD   HL, (HsTextPtr)
                LD   A, (HL)
                INC  HL
                LD   (HsTextPtr), HL
                OR   A
                RET  Z
                CP   32
                JR   NC, .range_hi
                LD   A, '?'
                JR   .haveChar
.range_hi:      CP   127
                JR   C, .haveChar
                LD   A, '?'
.haveChar:      SUB  32
                CALL Hsc_GlyphPtrFromA
                PUSH HL
                POP  IX
                LD   A, (IX+10)
                LD   (HsGlyphAdv), A
                LD   HL, (HsTextPtr)
                DEC  HL
                LD   A, (HL)
                CP   ' '
                CALL NZ, Hsc_EmitGlyph
                LD   A, (HsGlyphAdv)
                CALL Hsc_BytePixelsToVertexDE
                LD   HL, (HsPenX)
                ADD  HL, DE
                LD   (HsPenX), HL
                LD   A, (HsTextLeft)
                DEC  A
                LD   (HsTextLeft), A
                JR   .loop

Hsc_GlyphPtrFromA:
                LD   E, A
                LD   D, 0
                LD   H, D
                LD   L, E
                ADD  HL, HL
                ADD  HL, HL
                PUSH HL
                ADD  HL, HL
                POP  DE
                ADD  HL, DE                    ; *12
                LD   DE, HsGlyphTable
                ADD  HL, DE
                RET

Hsc_EmitGlyph:
                CALL Hsc_CmdFlushIfNear
                LD   E, (IX+0)
                LD   D, (IX+1)
                LD   A, (IX+2)
                LD   H, #01
                LD   L, A
                CALL Render_CmdBufWrite32

                LD   A, (IX+6)
                LD   L, A
                LD   H, 0
                LD   (HsSpriteW), HL
                LD   A, (IX+7)
                LD   L, A
                LD   H, 0
                LD   (HsSpriteH), HL
                LD   A, (IX+8)
                LD   L, A
                LD   H, 0
                LD   (HsSpriteSizeW), HL
                LD   A, (IX+9)
                LD   L, A
                LD   H, 0
                LD   (HsSpriteSizeH), HL

                LD   HL, (HsSpriteW)
                CALL Hsc_WidthShift7ToA
                ADD  A, #78
                LD   L, A
                LD   H, #07
                CALL Hsc_LowWordFromWH
                CALL Render_CmdBufWrite32

                LD   HL, (HsSpriteSizeW)
                CALL Hsc_WidthShift7ToA
                LD   L, A
                LD   H, #08
                CALL Hsc_LowWordFromSizeWH
                CALL Render_CmdBufWrite32

                LD   HL, (HsPenX)
                LD   (RenderPathVertexX), HL
                LD   A, (IX+11)
                CALL Hsc_SignedBytePixelsToVertexDE
                LD   HL, (HsPenY)
                ADD  HL, DE
                LD   (RenderPathVertexY), HL
                JP   Render_WriteVertex2FCmd

Hsc_BytePixelsToVertexDE:
                LD   E, A
                LD   D, 0
                JR   Hsc_ShiftDELeft4

Hsc_SignedBytePixelsToVertexDE:
                LD   E, A
                LD   D, 0
                BIT  7, E
                JR   Z, Hsc_ShiftDELeft4
                LD   D, #FF

Hsc_ShiftDELeft4:
                SLA  E
                RL   D
                SLA  E
                RL   D
                SLA  E
                RL   D
                SLA  E
                RL   D
                RET

Hsc_NumberToText:
                LD   (HsNumVal), HL
                LD   IX, HsNumDivisors
                LD   HL, HsNumBuf
                LD   (HsNumOut), HL
                XOR  A
                LD   (HsNumStarted), A
.digit:         LD   E, (IX+0)
                LD   D, (IX+1)
                LD   A, E
                OR   D
                JR   Z, .ones
                XOR  A
                LD   (HsNumDigit), A
.subloop:       LD   HL, (HsNumVal)
                OR   A
                SBC  HL, DE
                JR   C, .emit
                LD   (HsNumVal), HL
                LD   A, (HsNumDigit)
                INC  A
                LD   (HsNumDigit), A
                JR   .subloop
.emit:          LD   A, (HsNumDigit)
                OR   A
                JR   NZ, .store
                LD   A, (HsNumStarted)
                OR   A
                JR   Z, .next
                XOR  A
.store:         ADD  A, '0'
                LD   HL, (HsNumOut)
                LD   (HL), A
                INC  HL
                LD   (HsNumOut), HL
                LD   A, 1
                LD   (HsNumStarted), A
.next:          INC  IX
                INC  IX
                JR   .digit
.ones:          LD   A, (HsNumVal)
                ADD  A, '0'
                LD   HL, (HsNumOut)
                LD   (HL), A
                INC  HL
                LD   (HL), 0
                RET

; HiScores direct-RAM_DL flushing. CMD_ADDRESS_PTR is in slot2/CorePage+1.
HSC_CMD_FLUSH_PTR EQU CMD_ADDRESS_PTR + #0800
Hsc_CmdFlushIfNear:
                PUSH AF
                PUSH BC
                PUSH DE
                PUSH HL
                LD   HL, (FT.Coprocessor.BufferPtr)
                LD   DE, HSC_CMD_FLUSH_PTR
                OR   A
                SBC  HL, DE
                JR   C, .done
                CALL Hsc_DlFlush
.done:          POP  HL
                POP  DE
                POP  BC
                POP  AF
                RET

Hsc_DlFlush:
                PUSH AF
                PUSH BC
                PUSH DE
                PUSH HL
                LD   HL, (FT.Coprocessor.BufferPtr)
                LD   DE, CMD_ADDRESS_PTR
                OR   A
                SBC  HL, DE
                LD   A, H
                OR   L
                JR   Z, .done
                LD   B, H
                LD   C, L
                LD   A, CorePage + 1
                LD   (Render_DmaSourcePage), A
                LD   HL, CMD_ADDRESS_PTR
                LD   A, #30
                LD   DE, (HscDlRamLo)
                CALL Render_WriteMem_DMA
                LD   HL, (FT.Coprocessor.BufferPtr)
                LD   DE, CMD_ADDRESS_PTR
                OR   A
                SBC  HL, DE
                LD   DE, (HscDlRamLo)
                ADD  HL, DE
                LD   (HscDlRamLo), HL
                LD   HL, CMD_ADDRESS_PTR
                LD   (FT.Coprocessor.BufferPtr), HL
.done:          POP  HL
                POP  DE
                POP  BC
                POP  AF
                RET

Hsc_WidthShift7ToA:
                LD   A, H
                ADD  A, A
                LD   B, A
                LD   A, L
                RLCA
                AND  1
                OR   B
                RET

Hsc_LowWordFromWH:
                PUSH HL
                LD   HL, (HsSpriteW)
                LD   A, L
                AND  #7F
                ADD  A, A
                LD   D, A
                LD   E, 0
                LD   HL, (HsSpriteH)
                LD   E, L
                LD   A, D
                OR   H
                LD   D, A
                POP  HL
                RET

Hsc_LowWordFromSizeWH:
                PUSH HL
                LD   HL, (HsSpriteSizeW)
                LD   A, L
                AND  #7F
                ADD  A, A
                LD   D, A
                LD   E, 0
                LD   HL, (HsSpriteSizeH)
                LD   E, L
                LD   A, D
                OR   H
                LD   D, A
                POP  HL
                RET

HscUpscaleTransform_DL:
                FT_BITMAP_TRANSFORM_A 160
                FT_BITMAP_TRANSFORM_B 0
                FT_BITMAP_TRANSFORM_C 0
                FT_BITMAP_TRANSFORM_D 0
                FT_BITMAP_TRANSFORM_E 160
                FT_BITMAP_TRANSFORM_F 0
HscBitmapTransform_DL_SIZE EQU $ - HscUpscaleTransform_DL

HscNativeTextTransform_DL:
                FT_BITMAP_TRANSFORM_A 256
                FT_BITMAP_TRANSFORM_B 0
                FT_BITMAP_TRANSFORM_C 0
                FT_BITMAP_TRANSFORM_D 0
                FT_BITMAP_TRANSFORM_E 256
                FT_BITMAP_TRANSFORM_F 0
                ASSERT $ - HscNativeTextTransform_DL == HscBitmapTransform_DL_SIZE

HscFrameBegin_DL:
                FT_CLEAR_COLOR_RGB 0, 0, 0
                FT_CLEAR 1, 1, 1
                FT_SCISSOR_XY 0, 0
                FT_SCISSOR_SIZE 1024, 768
                FT_COLOR_RGB 255, 255, 255
                FT_COLOR_A 255
                FT_BITMAP_HANDLE 0
                FT_CELL 0
                FT_BITMAP_TRANSFORM_A 160
                FT_BITMAP_TRANSFORM_B 0
                FT_BITMAP_TRANSFORM_C 0
                FT_BITMAP_TRANSFORM_D 0
                FT_BITMAP_TRANSFORM_E 160
                FT_BITMAP_TRANSFORM_F 0
                FT_VERTEX_TRANSLATE_X 0
                FT_VERTEX_TRANSLATE_Y 0
                FT_BLEND_FUNC FT_SRC_ALPHA, FT_ONE_MINUS_SRC_ALPHA
                FT_BITMAP_LAYOUT_H 0, 0
                FT_BITMAP_SIZE_H 0, 0
                FT_BEGIN FT_BITMAPS
HscFrameBegin_DL_SIZE EQU $ - HscFrameBegin_DL

HscFrameEnd_DL:
                FT_END
HscFrameEnd_DL_SIZE EQU $ - HscFrameEnd_DL

HsIsCampaign:       DEFB 0
HsPressedOther:     DEFB 0
HsPressedExit:      DEFB 0
HsLmbLatch:         DEFB 0
HsAnimationFrame:   DEFB 0
HsInputX:           DEFW 0
HsInputY:           DEFW 0
HsTablePtr:         DEFW 0
HsTableCount:       DEFB 0
HsRowPtr:           DEFW 0
HsRowsLeft:         DEFB 0
HsRowY:             DEFW 0
HsMonsterY:         DEFW 0
HsPlayerPtr:        DEFW 0
HsScenarioPtr:      DEFW 0
HsDays:             DEFW 0
HsRating:           DEFW 0
HsMonster0Ptr:      DEFW 0
HsMonster1Ptr:      DEFW 0
HsBaseX:            DEFW 0
HsBaseY:            DEFW 0
HsSpriteW:          DEFW 0
HsSpriteH:          DEFW 0
HsSpriteSizeW:      DEFW 0
HsSpriteSizeH:      DEFW 0
HsTextPtr:          DEFW 0
HsTextLeft:         DEFB 0
HsPenX:             DEFW 0
HsPenY:             DEFW 0
HsGlyphAdv:         DEFB 0
HsNumVal:           DEFW 0
HsNumOut:           DEFW 0
HsNumStarted:       DEFB 0
HsNumDigit:         DEFB 0
HsNumBuf:           DEFS 6
HsNumDivisors:      DEFW 10000, 1000, 100, 10, 0
HscDlRamLo:         DEFW 0

                endif
