; Сгенерировано Source/Tools/hiscores_pack.py.
                ifndef _HMM2_GENERATED_HISCORES_META_
                define _HMM2_GENERATED_HISCORES_META_

HsBgTable:
                DEFW #0400
                DEFB #00
                DEFW 319, 319, 511, 511, #0000, #0000
                DEFW #9184
                DEFB #01
                DEFW 319, 319, 511, 511, #013F, #0000
                DEFW #1F08
                DEFB #03
                DEFW 2, 319, 4, 511, #027E, #0000
                DEFW #2188
                DEFB #03
                DEFW 319, 161, 511, 258, #0000, #013F
                DEFW #EA28
                DEFB #03
                DEFW 319, 161, 511, 258, #013F, #013F
                DEFW #B2C8
                DEFB #04
                DEFW 2, 161, 4, 258, #027E, #013F

HsTitleStandardTable:
                DEFW #B40C
                DEFB #04
                DEFW 319, 20, 511, 32, #0032, #001F
                DEFW #CCF8
                DEFB #04
                DEFW 221, 20, 354, 32, #0171, #001F

HsTitleCampaignTable:
                DEFW #DE3C
                DEFB #04
                DEFW 319, 20, 511, 32, #0032, #001F
                DEFW #F728
                DEFB #04
                DEFW 221, 20, 354, 32, #0171, #001F

HsButtonCampaignTable:
                DEFW #086C
                DEFB #05
                DEFW 27, 133, 44, 213, #0008, #013B
                DEFW #1674
                DEFB #05
                DEFW 27, 133, 44, 213, #0008, #013B

HsButtonStandardTable:
                DEFW #247C
                DEFB #05
                DEFW 27, 133, 44, 213, #0008, #013B
                DEFW #3284
                DEFB #05
                DEFW 27, 133, 44, 213, #0008, #013B

HsButtonExitTable:
                DEFW #408C
                DEFB #05
                DEFW 27, 133, 44, 213, #025C, #013B
                DEFW #4E94
                DEFB #05
                DEFW 27, 133, 44, 213, #025C, #013B

HsMonsterTable:
                DEFW #5C9C
                DEFB #05
                DEFW 31, 28, 50, 45, #FFE6, #FFE6
                DEFW #6000
                DEFB #05
                DEFW 38, 25, 61, 40, #FFE5, #FFE7
                DEFW #63B8
                DEFB #05
                DEFW 38, 25, 61, 40, #FFE5, #FFE7
                DEFW #6770
                DEFB #05
                DEFW 39, 25, 63, 40, #FFE5, #FFE7
                DEFW #6B40
                DEFB #05
                DEFW 39, 25, 63, 40, #FFE5, #FFE7
                DEFW #6F10
                DEFB #05
                DEFW 40, 25, 64, 40, #FFE5, #FFE7
                DEFW #72F8
                DEFB #05
                DEFW 36, 23, 58, 37, #FFE9, #FFE7
                DEFW #7634
                DEFB #05
                DEFW 32, 26, 52, 42, #FFE6, #FFE8
                DEFW #7974
                DEFB #05
                DEFW 28, 20, 45, 32, #FFED, #FFE9
                DEFW #7BA4
                DEFB #05
                DEFW 27, 21, 44, 34, #FFED, #FFE9
                DEFW #7DDC
                DEFB #05
                DEFW 26, 22, 42, 36, #FFED, #FFE9
                DEFW #8018
                DEFB #05
                DEFW 33, 21, 53, 34, #FFE8, #FFE8
                DEFW #82D0
                DEFB #05
                DEFW 36, 24, 58, 39, #FFE5, #FFE8
                DEFW #8630
                DEFB #05
                DEFW 36, 24, 58, 39, #FFE5, #FFE8
                DEFW #8990
                DEFB #05
                DEFW 35, 28, 56, 45, #FFE4, #FFE6
                DEFW #8D64
                DEFB #05
                DEFW 36, 21, 58, 34, #FFE3, #FFE6
                DEFW #9058
                DEFB #05
                DEFW 37, 23, 60, 37, #FFE2, #FFE6
                DEFW #93AC
                DEFB #05
                DEFW 37, 24, 60, 39, #FFE2, #FFE6
                DEFW #9724
                DEFB #05
                DEFW 37, 23, 60, 37, #FFE2, #FFE6
                DEFW #9A78
                DEFB #05
                DEFW 36, 24, 58, 39, #FFE2, #FFE6
                DEFW #9DD8
                DEFB #05
                DEFW 36, 23, 58, 37, #FFE2, #FFE6
                DEFW #A114
                DEFB #05
                DEFW 31, 26, 50, 42, #FFE7, #FFE8
                DEFW #A43C
                DEFB #05
                DEFW 31, 22, 50, 36, #FFEA, #FFE8
                DEFW #A6E8
                DEFB #05
                DEFW 32, 21, 52, 34, #FFE8, #FFE9
                DEFW #A988
                DEFB #05
                DEFW 33, 21, 53, 34, #FFE8, #FFE9
                DEFW #AC40
                DEFB #05
                DEFW 31, 21, 50, 34, #FFEA, #FFE8
                DEFW #AECC
                DEFB #05
                DEFW 33, 21, 53, 34, #FFEA, #FFE8
                DEFW #B184
                DEFB #05
                DEFW 33, 20, 53, 32, #FFEA, #FFE8
                DEFW #B418
                DEFB #05
                DEFW 40, 28, 64, 45, #FFE5, #FFE6
                DEFW #B878
                DEFB #05
                DEFW 44, 27, 71, 44, #FFE8, #FFE4
                DEFW #BD1C
                DEFB #05
                DEFW 44, 26, 71, 42, #FFE8, #FFE4
                DEFW #C194
                DEFB #05
                DEFW 44, 24, 71, 39, #FFE8, #FFE4
                DEFW #C5B4
                DEFB #05
                DEFW 43, 26, 69, 42, #FFE8, #FFE5
                DEFW #CA14
                DEFB #05
                DEFW 42, 25, 68, 40, #FFE8, #FFE6
                DEFW #CE30
                DEFB #05
                DEFW 42, 25, 68, 40, #FFE8, #FFE6
                DEFW #D24C
                DEFB #05
                DEFW 33, 28, 53, 45, #FFE6, #FFE6
                DEFW #D5E8
                DEFB #05
                DEFW 20, 23, 32, 37, #FFF5, #FFE7
                DEFW #D7B4
                DEFB #05
                DEFW 28, 25, 45, 40, #FFED, #FFE7
                DEFW #DA70
                DEFB #05
                DEFW 28, 24, 45, 39, #FFED, #FFE7
                DEFW #DD10
                DEFB #05
                DEFW 20, 23, 32, 37, #FFF5, #FFE7
                DEFW #DEDC
                DEFB #05
                DEFW 22, 23, 36, 37, #FFF6, #FFE7
                DEFW #E0D8
                DEFB #05
                DEFW 23, 23, 37, 37, #FFF6, #FFE7
                DEFW #E2EC
                DEFB #05
                DEFW 34, 25, 55, 40, #FFE7, #FFE9
                DEFW #E640
                DEFB #05
                DEFW 30, 25, 48, 40, #FFED, #FFE6
                DEFW #E930
                DEFB #05
                DEFW 38, 23, 61, 37, #FFE5, #FFE5
                DEFW #EC9C
                DEFB #05
                DEFW 38, 23, 61, 37, #FFE5, #FFE5
                DEFW #F008
                DEFB #05
                DEFW 30, 25, 48, 40, #FFED, #FFE6
                DEFW #F2F8
                DEFB #05
                DEFW 31, 25, 50, 40, #FFEB, #FFE6
                DEFW #F600
                DEFB #05
                DEFW 31, 25, 50, 40, #FFEB, #FFE6
                DEFW #F908
                DEFB #05
                DEFW 32, 27, 52, 44, #FFE6, #FFE7
                DEFW #FC68
                DEFB #05
                DEFW 31, 26, 50, 42, #FFEF, #FFE4
                DEFW #FF90
                DEFB #05
                DEFW 31, 26, 50, 42, #FFEF, #FFE4
                DEFW #02B8
                DEFB #06
                DEFW 32, 26, 52, 42, #FFED, #FFE4
                DEFW #05F8
                DEFB #06
                DEFW 42, 27, 68, 44, #FFE4, #FFE3
                DEFW #0A68
                DEFB #06
                DEFW 42, 27, 68, 44, #FFE4, #FFE3
                DEFW #0ED8
                DEFB #06
                DEFW 42, 27, 68, 44, #FFE4, #FFE3
                DEFW #1348
                DEFB #06
                DEFW 33, 30, 53, 48, #FFE5, #FFE4
                DEFW #1728
                DEFB #06
                DEFW 44, 32, 71, 52, #FFDE, #FFDF
                DEFW #1CA8
                DEFB #06
                DEFW 45, 35, 72, 56, #FFDC, #FFDE
                DEFW #22D0
                DEFB #06
                DEFW 49, 34, 79, 55, #FFD8, #FFDD
                DEFW #2954
                DEFB #06
                DEFW 47, 31, 76, 50, #FFDF, #FFE2
                DEFW #2F08
                DEFB #06
                DEFW 48, 34, 77, 55, #FFDB, #FFDF
                DEFW #3568
                DEFB #06
                DEFW 47, 32, 76, 52, #FFDA, #FFDF
                DEFW #3B48
                DEFB #06
                DEFW 31, 29, 50, 47, #FFE6, #FFE5
                DEFW #3ECC
                DEFB #06
                DEFW 39, 28, 63, 45, #FFE6, #FFE4
                DEFW #4310
                DEFB #06
                DEFW 39, 28, 63, 45, #FFE6, #FFE4
                DEFW #4754
                DEFB #06
                DEFW 39, 28, 63, 45, #FFE6, #FFE4
                DEFW #4B98
                DEFB #06
                DEFW 39, 28, 63, 45, #FFE6, #FFE4
                DEFW #4FDC
                DEFB #06
                DEFW 40, 21, 64, 34, #FFE4, #FFE7
                DEFW #5324
                DEFB #06
                DEFW 40, 19, 64, 31, #FFE4, #FFEB
                DEFW #561C
                DEFB #06
                DEFW 31, 31, 50, 50, #FFE6, #FFE3
                DEFW #59E0
                DEFB #06
                DEFW 39, 29, 63, 47, #FFE6, #FFE3
                DEFW #5E4C
                DEFB #06
                DEFW 39, 29, 63, 47, #FFE6, #FFE3
                DEFW #62B8
                DEFB #06
                DEFW 39, 29, 63, 47, #FFE6, #FFE3
                DEFW #6724
                DEFB #06
                DEFW 39, 29, 63, 47, #FFE6, #FFE3
                DEFW #6B90
                DEFB #06
                DEFW 40, 25, 64, 40, #FFE4, #FFE3
                DEFW #6F78
                DEFB #06
                DEFW 40, 27, 64, 44, #FFE4, #FFE3
                DEFW #73B0
                DEFB #06
                DEFW 37, 21, 60, 34, #FFEA, #FFED
                DEFW #76BC
                DEFB #06
                DEFW 32, 17, 52, 28, #FFEA, #FFF1
                DEFW #78DC
                DEFB #06
                DEFW 33, 17, 53, 28, #FFE9, #FFF1
                DEFW #7B10
                DEFB #06
                DEFW 34, 17, 55, 28, #FFE8, #FFF1
                DEFW #7D54
                DEFB #06
                DEFW 32, 16, 52, 26, #FFEA, #FFF1
                DEFW #7F54
                DEFB #06
                DEFW 29, 16, 47, 26, #FFED, #FFF1
                DEFW #8124
                DEFB #06
                DEFW 27, 16, 44, 26, #FFEF, #FFF1
                DEFW #82D4
                DEFB #06
                DEFW 31, 28, 50, 45, #FFE6, #FFE6
                DEFW #8638
                DEFB #06
                DEFW 35, 25, 56, 40, #FFE9, #FFE6
                DEFW #89A4
                DEFB #06
                DEFW 41, 24, 66, 39, #FFE3, #FFE5
                DEFW #8D7C
                DEFB #06
                DEFW 41, 24, 66, 39, #FFE3, #FFE5
                DEFW #9154
                DEFB #06
                DEFW 33, 25, 53, 40, #FFE9, #FFE6
                DEFW #9490
                DEFB #06
                DEFW 33, 25, 53, 40, #FFE9, #FFE6
                DEFW #97CC
                DEFB #06
                DEFW 33, 25, 53, 40, #FFE9, #FFE6
                DEFW #9B08
                DEFB #06
                DEFW 34, 30, 55, 48, #FFE6, #FFE4
                DEFW #9F04
                DEFB #06
                DEFW 45, 38, 72, 61, #FFDF, #FFD9
                DEFW #A5B4
                DEFB #06
                DEFW 45, 38, 72, 61, #FFDD, #FFDB
                DEFW #AC64
                DEFB #06
                DEFW 52, 35, 84, 56, #FFD9, #FFDC
                DEFW #B380
                DEFB #06
                DEFW 48, 36, 77, 58, #FFE0, #FFDD
                DEFW #BA40
                DEFB #06
                DEFW 52, 37, 84, 60, #FFDC, #FFDC
                DEFW #C1C4
                DEFB #06
                DEFW 52, 35, 84, 56, #FFDB, #FFDC
                DEFW #C8E0
                DEFB #06
                DEFW 32, 27, 52, 44, #FFE6, #FFE7
                DEFW #CC40
                DEFB #06
                DEFW 31, 28, 50, 45, #FFEF, #FFE2
                DEFW #CFA4
                DEFB #06
                DEFW 31, 28, 50, 45, #FFEF, #FFE2
                DEFW #D308
                DEFB #06
                DEFW 33, 28, 53, 45, #FFED, #FFE2
                DEFW #D6A4
                DEFB #06
                DEFW 42, 29, 68, 47, #FFE4, #FFE1
                DEFW #DB68
                DEFB #06
                DEFW 42, 29, 68, 47, #FFE4, #FFE1
                DEFW #E02C
                DEFB #06
                DEFW 42, 29, 68, 47, #FFE4, #FFE1
                DEFW #E4F0
                DEFB #06
                DEFW 46, 30, 74, 48, #FFDF, #FFE4
                DEFW #EA54
                DEFB #06
                DEFW 46, 25, 74, 40, #FFE0, #FFE4
                DEFW #EED4
                DEFB #06
                DEFW 46, 25, 74, 40, #FFE0, #FFE4
                DEFW #F354
                DEFB #06
                DEFW 46, 25, 74, 40, #FFE0, #FFE4
                DEFW #F7D4
                DEFB #06
                DEFW 45, 25, 72, 40, #FFE0, #FFE4
                DEFW #FC3C
                DEFB #06
                DEFW 46, 22, 74, 36, #FFE0, #FFE4
                DEFW #0030
                DEFB #07
                DEFW 44, 22, 71, 36, #FFE2, #FFE4
                DEFW #03F8
                DEFB #07
                DEFW 37, 29, 60, 47, #FFE3, #FFE5
                DEFW #082C
                DEFB #07
                DEFW 37, 28, 60, 45, #FFE3, #FFE5
                DEFW #0C38
                DEFB #07
                DEFW 37, 28, 60, 45, #FFE3, #FFE5
                DEFW #1044
                DEFB #07
                DEFW 37, 28, 60, 45, #FFE3, #FFE5
                DEFW #1450
                DEFB #07
                DEFW 36, 27, 58, 44, #FFE4, #FFE5
                DEFW #181C
                DEFB #07
                DEFW 38, 27, 61, 44, #FFE2, #FFE5
                DEFW #1C20
                DEFB #07
                DEFW 38, 27, 61, 44, #FFE2, #FFE5
                DEFW #2024
                DEFB #07
                DEFW 37, 32, 60, 52, #FFE1, #FFE2
                DEFW #24C4
                DEFB #07
                DEFW 44, 30, 71, 48, #FFE1, #FFE3
                DEFW #29EC
                DEFB #07
                DEFW 42, 30, 68, 48, #FFE3, #FFE3
                DEFW #2ED8
                DEFB #07
                DEFW 44, 30, 71, 48, #FFE1, #FFE3
                DEFW #3400
                DEFB #07
                DEFW 41, 31, 66, 50, #FFE3, #FFE2
                DEFW #38F8
                DEFB #07
                DEFW 41, 29, 66, 47, #FFE3, #FFE1
                DEFW #3DA0
                DEFB #07
                DEFW 39, 32, 63, 52, #FFE3, #FFDF
                DEFW #4280
                DEFB #07
                DEFW 44, 31, 71, 50, #FFDD, #FFE3
                DEFW #47D4
                DEFB #07
                DEFW 50, 24, 80, 39, #FFDD, #FFE4
                DEFW #4C84
                DEFB #07
                DEFW 50, 24, 80, 39, #FFDD, #FFE4
                DEFW #5134
                DEFB #07
                DEFW 50, 21, 80, 34, #FFDD, #FFE3
                DEFW #5550
                DEFB #07
                DEFW 50, 24, 80, 39, #FFDD, #FFE4
                DEFW #5A00
                DEFB #07
                DEFW 52, 25, 84, 40, #FFDB, #FFE3
                DEFW #5F14
                DEFB #07
                DEFW 53, 30, 85, 48, #FFDA, #FFE2
                DEFW #654C
                DEFB #07
                DEFW 31, 24, 50, 39, #FFE6, #FFEA
                DEFW #6834
                DEFB #07
                DEFW 35, 27, 56, 44, #FFE9, #FFE4
                DEFW #6BE8
                DEFB #07
                DEFW 41, 25, 66, 40, #FFE3, #FFE4
                DEFW #6FEC
                DEFB #07
                DEFW 41, 25, 66, 40, #FFE3, #FFE4
                DEFW #73F0
                DEFB #07
                DEFW 33, 27, 53, 44, #FFE9, #FFE4
                DEFW #776C
                DEFB #07
                DEFW 33, 27, 53, 44, #FFE9, #FFE4
                DEFW #7AE8
                DEFB #07
                DEFW 33, 27, 53, 44, #FFE9, #FFE4
                DEFW #7E64
                DEFB #07
                DEFW 48, 35, 77, 56, #FFE0, #FFDF
                DEFW #84F4
                DEFB #07
                DEFW 45, 24, 72, 39, #FFE3, #FFE6
                DEFW #892C
                DEFB #07
                DEFW 41, 24, 66, 39, #FFE7, #FFE6
                DEFW #8D04
                DEFB #07
                DEFW 39, 23, 63, 37, #FFE9, #FFE6
                DEFW #9088
                DEFB #07
                DEFW 46, 23, 74, 37, #FFE2, #FFE6
                DEFW #94AC
                DEFB #07
                DEFW 48, 23, 77, 37, #FFE0, #FFE6
                DEFW #98FC
                DEFB #07
                DEFW 48, 21, 77, 34, #FFE0, #FFE7
                DEFW #9CEC
                DEFB #07
                DEFW 37, 32, 60, 52, #FFE1, #FFE2
                DEFW #A18C
                DEFB #07
                DEFW 44, 32, 71, 52, #FFE1, #FFE1
                DEFW #A70C
                DEFB #07
                DEFW 42, 31, 68, 50, #FFE3, #FFE2
                DEFW #AC24
                DEFB #07
                DEFW 44, 31, 71, 50, #FFE1, #FFE2
                DEFW #B178
                DEFB #07
                DEFW 41, 32, 66, 52, #FFE3, #FFE1
                DEFW #B698
                DEFB #07
                DEFW 41, 29, 66, 47, #FFE3, #FFE1
                DEFW #BB40
                DEFB #07
                DEFW 39, 32, 63, 52, #FFE3, #FFDF
                DEFW #C020
                DEFB #07
                DEFW 32, 20, 52, 32, #FFEA, #FFEE
                DEFW #C2A0
                DEFB #07
                DEFW 40, 21, 64, 34, #FFE8, #FFEA
                DEFW #C5E8
                DEFB #07
                DEFW 36, 22, 58, 36, #FFEC, #FFEB
                DEFW #C900
                DEFB #07
                DEFW 42, 19, 68, 31, #FFE7, #FFEB
                DEFW #CC20
                DEFB #07
                DEFW 42, 24, 68, 39, #FFE7, #FFE9
                DEFW #D010
                DEFB #07
                DEFW 40, 24, 64, 39, #FFE7, #FFE9
                DEFW #D3D0
                DEFB #07
                DEFW 38, 23, 61, 37, #FFE8, #FFE8
                DEFW #D73C
                DEFB #07
                DEFW 36, 32, 58, 52, #FFE4, #FFE2
                DEFW #DBBC
                DEFB #07
                DEFW 40, 31, 64, 50, #FFE2, #FFE2
                DEFW #E094
                DEFB #07
                DEFW 36, 31, 58, 50, #FFE6, #FFE2
                DEFW #E4F0
                DEFB #07
                DEFW 39, 31, 63, 50, #FFE3, #FFE2
                DEFW #E9AC
                DEFB #07
                DEFW 39, 31, 63, 50, #FFE2, #FFE2
                DEFW #EE68
                DEFB #07
                DEFW 39, 31, 63, 50, #FFE2, #FFE2
                DEFW #F324
                DEFB #07
                DEFW 39, 31, 63, 50, #FFE2, #FFE2
                DEFW #F7E0
                DEFB #07
                DEFW 38, 34, 61, 55, #FFE0, #FFE0
                DEFW #FCEC
                DEFB #07
                DEFW 35, 22, 56, 36, #FFE3, #FFE1
                DEFW #FFF0
                DEFB #07
                DEFW 38, 23, 61, 37, #FFE0, #FFE0
                DEFW #035C
                DEFB #08
                DEFW 39, 22, 63, 36, #FFDF, #FFE1
                DEFW #06B8
                DEFB #08
                DEFW 35, 21, 56, 34, #FFE3, #FFE1
                DEFW #0998
                DEFB #08
                DEFW 34, 25, 55, 40, #FFE3, #FFE1
                DEFW #0CEC
                DEFB #08
                DEFW 34, 26, 55, 42, #FFE3, #FFE1
                DEFW #1060
                DEFB #08
                DEFW 36, 32, 58, 52, #FFE4, #FFE2
                DEFW #14E0
                DEFB #08
                DEFW 40, 31, 64, 50, #FFE2, #FFE2
                DEFW #19B8
                DEFB #08
                DEFW 36, 31, 58, 50, #FFE6, #FFE2
                DEFW #1E14
                DEFB #08
                DEFW 39, 31, 63, 50, #FFE3, #FFE2
                DEFW #22D0
                DEFB #08
                DEFW 39, 31, 63, 50, #FFE2, #FFE2
                DEFW #278C
                DEFB #08
                DEFW 39, 31, 63, 50, #FFE2, #FFE2
                DEFW #2C48
                DEFB #08
                DEFW 39, 31, 63, 50, #FFE2, #FFE2
                DEFW #3104
                DEFB #08
                DEFW 36, 31, 58, 50, #FFE2, #FFE3
                DEFW #3560
                DEFB #08
                DEFW 41, 26, 66, 42, #FFE1, #FFE3
                DEFW #398C
                DEFB #08
                DEFW 29, 28, 47, 45, #FFED, #FFE2
                DEFW #3CB8
                DEFB #08
                DEFW 29, 28, 47, 45, #FFED, #FFE2
                DEFW #3FE4
                DEFB #08
                DEFW 42, 26, 68, 42, #FFE1, #FFE3
                DEFW #4428
                DEFB #08
                DEFW 43, 24, 69, 39, #FFE1, #FFE3
                DEFW #4830
                DEFB #08
                DEFW 45, 24, 72, 39, #FFE1, #FFE3
                DEFW #4C68
                DEFB #08
                DEFW 45, 33, 72, 53, #FFDF, #FFE1
                DEFW #5238
                DEFB #08
                DEFW 49, 33, 79, 53, #FFDE, #FFE0
                DEFW #588C
                DEFB #08
                DEFW 49, 34, 79, 55, #FFDE, #FFDF
                DEFW #5F10
                DEFB #08
                DEFW 49, 34, 79, 55, #FFDE, #FFDF
                DEFW #6594
                DEFB #08
                DEFW 46, 33, 74, 53, #FFE0, #FFE0
                DEFW #6B84
                DEFB #08
                DEFW 49, 33, 79, 53, #FFDE, #FFE0
                DEFW #71D8
                DEFB #08
                DEFW 45, 34, 72, 55, #FFE0, #FFE0
                DEFW #77D4
                DEFB #08
                DEFW 38, 32, 61, 52, #FFE1, #FFE2
                DEFW #7C94
                DEFB #08
                DEFW 24, 26, 39, 42, #FFF2, #FFE7
                DEFW #7F04
                DEFB #08
                DEFW 29, 26, 47, 42, #FFED, #FFE7
                DEFW #81F8
                DEFB #08
                DEFW 30, 26, 48, 42, #FFEC, #FFE7
                DEFW #8504
                DEFB #08
                DEFW 24, 24, 39, 39, #FFF4, #FFE9
                DEFW #8744
                DEFB #08
                DEFW 21, 24, 34, 39, #FFF7, #FFE9
                DEFW #893C
                DEFB #08
                DEFW 33, 24, 53, 39, #FFED, #FFE9
                DEFW #8C54
                DEFB #08
                DEFW 37, 31, 60, 50, #FFE1, #FFE3
                DEFW #90D0
                DEFB #08
                DEFW 36, 24, 58, 39, #FFE4, #FFE4
                DEFW #9430
                DEFB #08
                DEFW 36, 25, 58, 40, #FFE4, #FFE3
                DEFW #97B4
                DEFB #08
                DEFW 40, 30, 64, 48, #FFE0, #FFE3
                DEFW #9C64
                DEFB #08
                DEFW 40, 29, 64, 47, #FFE0, #FFE4
                DEFW #A0EC
                DEFB #08
                DEFW 38, 29, 61, 47, #FFE0, #FFE4
                DEFW #A53C
                DEFB #08
                DEFW 37, 29, 60, 47, #FFE0, #FFE4
                DEFW #A970
                DEFB #08
                DEFW 38, 34, 61, 55, #FFE0, #FFE0
                DEFW #AE7C
                DEFB #08
                DEFW 35, 23, 56, 37, #FFE3, #FFE0
                DEFW #B1A4
                DEFB #08
                DEFW 38, 23, 61, 37, #FFE0, #FFE0
                DEFW #B510
                DEFB #08
                DEFW 39, 23, 63, 37, #FFDF, #FFE0
                DEFW #B894
                DEFB #08
                DEFW 35, 22, 56, 36, #FFE3, #FFE0
                DEFW #BB98
                DEFB #08
                DEFW 34, 26, 55, 42, #FFE3, #FFE0
                DEFW #BF0C
                DEFB #08
                DEFW 34, 27, 55, 44, #FFE3, #FFE0
                DEFW #C2A4
                DEFB #08
                DEFW 38, 33, 61, 53, #FFE1, #FFE1
                DEFW #C78C
                DEFB #08
                DEFW 24, 26, 39, 42, #FFF2, #FFE7
                DEFW #C9FC
                DEFB #08
                DEFW 29, 26, 47, 42, #FFED, #FFE7
                DEFW #CCF0
                DEFB #08
                DEFW 30, 26, 48, 42, #FFEC, #FFE7
                DEFW #CFFC
                DEFB #08
                DEFW 24, 24, 39, 39, #FFF4, #FFE9
                DEFW #D23C
                DEFB #08
                DEFW 21, 24, 34, 39, #FFF7, #FFE9
                DEFW #D434
                DEFB #08
                DEFW 33, 24, 53, 39, #FFED, #FFE9
                DEFW #D74C
                DEFB #08
                DEFW 22, 34, 36, 55, #FFF1, #FFE0
                DEFW #DA38
                DEFB #08
                DEFW 1, 1, 2, 2, #0000, #0000
                DEFW #DA3C
                DEFB #08
                DEFW 1, 1, 2, 2, #0000, #0000
                DEFW #DA40
                DEFB #08
                DEFW 1, 1, 2, 2, #0000, #0000
                DEFW #DA44
                DEFB #08
                DEFW 1, 1, 2, 2, #0000, #0000
                DEFW #DA48
                DEFB #08
                DEFW 1, 1, 2, 2, #0000, #0000
                DEFW #DA4C
                DEFB #08
                DEFW 1, 1, 2, 2, #0000, #0000
                DEFW #DA50
                DEFB #08
                DEFW 37, 31, 60, 50, #FFE1, #FFE3
                DEFW #DECC
                DEFB #08
                DEFW 36, 24, 58, 39, #FFE4, #FFE4
                DEFW #E22C
                DEFB #08
                DEFW 36, 25, 58, 40, #FFE4, #FFE3
                DEFW #E5B0
                DEFB #08
                DEFW 40, 30, 64, 48, #FFE0, #FFE3
                DEFW #EA60
                DEFB #08
                DEFW 40, 29, 64, 47, #FFE0, #FFE4
                DEFW #EEE8
                DEFB #08
                DEFW 38, 29, 61, 47, #FFE0, #FFE4
                DEFW #F338
                DEFB #08
                DEFW 37, 29, 60, 47, #FFE0, #FFE4
                DEFW #F76C
                DEFB #08
                DEFW 22, 34, 36, 55, #FFF2, #FFE0
                DEFW #FA58
                DEFB #08
                DEFW 1, 1, 2, 2, #0000, #0000
                DEFW #FA5C
                DEFB #08
                DEFW 1, 1, 2, 2, #0000, #0000
                DEFW #FA60
                DEFB #08
                DEFW 1, 1, 2, 2, #0000, #0000
                DEFW #FA64
                DEFB #08
                DEFW 1, 1, 2, 2, #0000, #0000
                DEFW #FA68
                DEFB #08
                DEFW 1, 1, 2, 2, #0000, #0000
                DEFW #FA6C
                DEFB #08
                DEFW 1, 1, 2, 2, #0000, #0000
                DEFW #FA70
                DEFB #08
                DEFW 26, 14, 42, 23, #FFE0, #FFF3
                DEFW #FBDC
                DEFB #08
                DEFW 43, 35, 69, 56, #FFDC, #FFDF
                DEFW #01C0
                DEFB #09
                DEFW 44, 35, 71, 56, #FFDC, #FFDF
                DEFW #07C4
                DEFB #09
                DEFW 44, 36, 71, 58, #FFDC, #FFDE
                DEFW #0DF4
                DEFB #09
                DEFW 42, 36, 68, 58, #FFE0, #FFDF
                DEFW #13DC
                DEFB #09
                DEFW 44, 36, 71, 58, #FFDC, #FFDE
                DEFW #1A0C
                DEFB #09
                DEFW 44, 36, 71, 58, #FFDC, #FFDF
                DEFW #203C
                DEFB #09
                DEFW 14, 32, 23, 52, #FFF9, #FFE1
                DEFW #21FC
                DEFB #09
                DEFW 14, 28, 23, 45, #FFF9, #FFE1
                DEFW #2384
                DEFB #09
                DEFW 14, 28, 23, 45, #FFF9, #FFE1
                DEFW #250C
                DEFB #09
                DEFW 14, 28, 23, 45, #FFF9, #FFE1
                DEFW #2694
                DEFB #09
                DEFW 14, 29, 23, 47, #FFF9, #FFE0
                DEFW #282C
                DEFB #09
                DEFW 13, 29, 21, 47, #FFFA, #FFE0
                DEFW #29A8
                DEFB #09
                DEFW 14, 28, 23, 45, #FFF9, #FFE1
                DEFW #2B30
                DEFB #09
                DEFW 22, 34, 36, 55, #FFF1, #FFE0
                DEFW #2E1C
                DEFB #09
                DEFW 1, 1, 2, 2, #0000, #0000
                DEFW #2E20
                DEFB #09
                DEFW 1, 1, 2, 2, #0000, #0000
                DEFW #2E24
                DEFB #09
                DEFW 1, 1, 2, 2, #0000, #0000
                DEFW #2E28
                DEFB #09
                DEFW 1, 1, 2, 2, #0000, #0000
                DEFW #2E2C
                DEFB #09
                DEFW 1, 1, 2, 2, #0000, #0000
                DEFW #2E30
                DEFB #09
                DEFW 1, 1, 2, 2, #0000, #0000
                DEFW #2E34
                DEFB #09
                DEFW 37, 29, 60, 47, #FFE5, #FFE5
                DEFW #3268
                DEFB #09
                DEFW 41, 30, 66, 48, #FFE3, #FFE3
                DEFW #3738
                DEFB #09
                DEFW 41, 30, 66, 48, #FFE4, #FFE3
                DEFW #3C08
                DEFB #09
                DEFW 40, 30, 64, 48, #FFE4, #FFE3
                DEFW #40B8
                DEFB #09
                DEFW 41, 31, 66, 50, #FFE2, #FFE2
                DEFW #45B0
                DEFB #09
                DEFW 42, 32, 68, 52, #FFE1, #FFE1
                DEFW #4AF0
                DEFB #09
                DEFW 42, 32, 68, 52, #FFE2, #FFE1
                DEFW #5030
                DEFB #09
                DEFW 47, 34, 76, 55, #FFDF, #FFE0
                DEFW #5670
                DEFB #09
                DEFW 46, 34, 74, 55, #FFE0, #FFDF
                DEFW #5C8C
                DEFB #09
                DEFW 47, 34, 76, 55, #FFDF, #FFDF
                DEFW #62CC
                DEFB #09
                DEFW 47, 34, 76, 55, #FFDF, #FFDF
                DEFW #690C
                DEFB #09
                DEFW 48, 34, 77, 55, #FFDE, #FFDF
                DEFW #6F6C
                DEFB #09
                DEFW 49, 34, 79, 55, #FFDD, #FFDF
                DEFW #75F0
                DEFB #09
                DEFW 47, 34, 76, 55, #FFDF, #FFDF
                DEFW #7C30
                DEFB #09
                DEFW 39, 34, 63, 55, #FFDF, #FFE0
                DEFW #8160
                DEFB #09
                DEFW 44, 32, 71, 52, #FFDE, #FFDF
                DEFW #86E0
                DEFB #09
                DEFW 44, 32, 71, 52, #FFDE, #FFDF
                DEFW #8C60
                DEFB #09
                DEFW 45, 32, 72, 52, #FFDD, #FFDF
                DEFW #9200
                DEFB #09
                DEFW 45, 32, 72, 52, #FFDE, #FFDF
                DEFW #97A0
                DEFB #09
                DEFW 45, 32, 72, 52, #FFDE, #FFDF
                DEFW #9D40
                DEFB #09
                DEFW 44, 32, 71, 52, #FFDE, #FFDF
                DEFW #A2C0
                DEFB #09
                DEFW 55, 34, 88, 55, #FFDC, #FFE0
                DEFW #AA10
                DEFB #09
                DEFW 45, 28, 72, 45, #FFE2, #FFE5
                DEFW #AEFC
                DEFB #09
                DEFW 46, 29, 74, 47, #FFE1, #FFE4
                DEFW #B434
                DEFB #09
                DEFW 48, 29, 77, 47, #FFE0, #FFE4
                DEFW #B9A4
                DEFB #09
                DEFW 41, 26, 66, 42, #FFE6, #FFE6
                DEFW #BDD0
                DEFB #09
                DEFW 42, 25, 68, 40, #FFE6, #FFE7
                DEFW #C1EC
                DEFB #09
                DEFW 42, 24, 68, 39, #FFE6, #FFE7
                DEFW #C5DC
                DEFB #09
                DEFW 33, 31, 53, 50, #FFE3, #FFE2
                DEFW #C9DC
                DEFB #09
                DEFW 38, 32, 61, 52, #FFE1, #FFE2
                DEFW #CE9C
                DEFB #09
                DEFW 37, 31, 60, 50, #FFE3, #FFE2
                DEFW #D318
                DEFB #09
                DEFW 39, 32, 63, 52, #FFE0, #FFE2
                DEFW #D7F8
                DEFB #09
                DEFW 38, 32, 61, 52, #FFE1, #FFE2
                DEFW #DCB8
                DEFB #09
                DEFW 38, 32, 61, 52, #FFE1, #FFE2
                DEFW #E178
                DEFB #09
                DEFW 38, 32, 61, 52, #FFE1, #FFE2
                DEFW #E638
                DEFB #09
                DEFW 42, 32, 68, 52, #FFE1, #FFE2
                DEFW #EB78
                DEFB #09
                DEFW 36, 20, 58, 32, #FFE0, #FFE3
                DEFW #EE48
                DEFB #09
                DEFW 37, 21, 60, 34, #FFDF, #FFE2
                DEFW #F154
                DEFB #09
                DEFW 36, 21, 58, 34, #FFE0, #FFE2
                DEFW #F448
                DEFB #09
                DEFW 29, 20, 47, 32, #FFE7, #FFE3
                DEFW #F68C
                DEFB #09
                DEFW 29, 20, 47, 32, #FFE7, #FFE3
                DEFW #F8D0
                DEFB #09
                DEFW 29, 20, 47, 32, #FFE7, #FFE3
                DEFW #FB14
                DEFB #09
                DEFW 15, 9, 24, 15, #FFE8, #FFF7
                DEFW #FB9C
                DEFB #09
                DEFW 39, 30, 63, 48, #FFE4, #FFE4
                DEFW #0030
                DEFB #0A
                DEFW 41, 31, 66, 50, #FFE3, #FFE3
                DEFW #0528
                DEFB #0A
                DEFW 41, 31, 66, 50, #FFE4, #FFE3
                DEFW #0A20
                DEFB #0A
                DEFW 41, 32, 66, 52, #FFE2, #FFE5
                DEFW #0F40
                DEFB #0A
                DEFW 42, 33, 68, 53, #FFE2, #FFE5
                DEFW #14AC
                DEFB #0A
                DEFW 41, 33, 66, 53, #FFE2, #FFE4
                DEFW #19F8
                DEFB #0A
                DEFW 38, 33, 61, 53, #FFE1, #FFE1
                DEFW #1EE0
                DEFB #0A
                DEFW 23, 29, 37, 47, #FFF2, #FFE2
                DEFW #217C
                DEFB #0A
                DEFW 25, 29, 40, 47, #FFF0, #FFE2
                DEFW #2454
                DEFB #0A
                DEFW 26, 29, 42, 47, #FFEF, #FFE2
                DEFW #2748
                DEFB #0A
                DEFW 39, 30, 63, 48, #FFE2, #FFE1
                DEFW #2BDC
                DEFB #0A
                DEFW 39, 30, 63, 48, #FFE2, #FFE1
                DEFW #3070
                DEFB #0A
                DEFW 39, 30, 63, 48, #FFE2, #FFE1
                DEFW #3504
                DEFB #0A
                DEFW 36, 31, 58, 50, #FFE2, #FFE3
                DEFW #3960
                DEFB #0A
                DEFW 41, 26, 66, 42, #FFE1, #FFE3
                DEFW #3D8C
                DEFB #0A
                DEFW 29, 28, 47, 45, #FFED, #FFE2
                DEFW #40B8
                DEFB #0A
                DEFW 29, 28, 47, 45, #FFED, #FFE2
                DEFW #43E4
                DEFB #0A
                DEFW 42, 26, 68, 42, #FFE1, #FFE3
                DEFW #4828
                DEFB #0A
                DEFW 43, 24, 69, 39, #FFE1, #FFE3
                DEFW #4C30
                DEFB #0A
                DEFW 45, 24, 72, 39, #FFE1, #FFE3
                DEFW #5068
                DEFB #0A
                DEFW 38, 34, 61, 55, #FFDF, #FFE0
                DEFW #5574
                DEFB #0A
                DEFW 44, 32, 71, 52, #FFDE, #FFDF
                DEFW #5AF4
                DEFB #0A
                DEFW 44, 32, 71, 52, #FFDE, #FFDF
                DEFW #6074
                DEFB #0A
                DEFW 45, 32, 72, 52, #FFDD, #FFDF
                DEFW #6614
                DEFB #0A
                DEFW 45, 32, 72, 52, #FFDE, #FFDF
                DEFW #6BB4
                DEFB #0A
                DEFW 45, 32, 72, 52, #FFDE, #FFDF
                DEFW #7154
                DEFB #0A
                DEFW 44, 32, 71, 52, #FFDE, #FFDF
                DEFW #76D4
                DEFB #0A
                DEFW 55, 34, 88, 55, #FFDC, #FFE0
                DEFW #7E24
                DEFB #0A
                DEFW 45, 30, 72, 48, #FFE2, #FFE3
                DEFW #836C
                DEFB #0A
                DEFW 46, 30, 74, 48, #FFE1, #FFE3
                DEFW #88D0
                DEFB #0A
                DEFW 48, 29, 77, 47, #FFE0, #FFE4
                DEFW #8E40
                DEFB #0A
                DEFW 41, 28, 66, 45, #FFE6, #FFE4
                DEFW #92BC
                DEFB #0A
                DEFW 42, 27, 68, 44, #FFE6, #FFE5
                DEFW #972C
                DEFB #0A
                DEFW 42, 25, 68, 40, #FFE6, #FFE6
                DEFW #9B48
                DEFB #0A
                DEFW 33, 31, 53, 50, #FFE3, #FFE2
                DEFW #9F48
                DEFB #0A
                DEFW 38, 32, 61, 52, #FFE1, #FFE2
                DEFW #A408
                DEFB #0A
                DEFW 37, 31, 60, 50, #FFE3, #FFE2
                DEFW #A884
                DEFB #0A
                DEFW 39, 32, 63, 52, #FFE0, #FFE2
                DEFW #AD64
                DEFB #0A
                DEFW 38, 32, 61, 52, #FFE1, #FFE2
                DEFW #B224
                DEFB #0A
                DEFW 38, 32, 61, 52, #FFE1, #FFE2
                DEFW #B6E4
                DEFB #0A
                DEFW 38, 32, 61, 52, #FFE1, #FFE2
                DEFW #BBA4
                DEFB #0A
                DEFW 14, 32, 23, 52, #FFF9, #FFE1
                DEFW #BD64
                DEFB #0A
                DEFW 14, 28, 23, 45, #FFF9, #FFE1
                DEFW #BEEC
                DEFB #0A
                DEFW 14, 28, 23, 45, #FFF9, #FFE1
                DEFW #C074
                DEFB #0A
                DEFW 14, 28, 23, 45, #FFF9, #FFE1
                DEFW #C1FC
                DEFB #0A
                DEFW 14, 29, 23, 47, #FFF9, #FFE0
                DEFW #C394
                DEFB #0A
                DEFW 13, 29, 21, 47, #FFFA, #FFE0
                DEFW #C510
                DEFB #0A
                DEFW 14, 28, 23, 45, #FFF9, #FFE1
                DEFW #C698
                DEFB #0A
                DEFW 42, 32, 68, 52, #FFE1, #FFE2
                DEFW #CBD8
                DEFB #0A
                DEFW 36, 20, 58, 32, #FFE0, #FFE3
                DEFW #CEA8
                DEFB #0A
                DEFW 37, 21, 60, 34, #FFDF, #FFE2
                DEFW #D1B4
                DEFB #0A
                DEFW 36, 21, 58, 34, #FFE0, #FFE2
                DEFW #D4A8
                DEFB #0A
                DEFW 29, 20, 47, 32, #FFE7, #FFE3
                DEFW #D6EC
                DEFB #0A
                DEFW 29, 20, 47, 32, #FFE7, #FFE3
                DEFW #D930
                DEFB #0A
                DEFW 29, 20, 47, 32, #FFE7, #FFE3
                DEFW #DB74
                DEFB #0A
                DEFW 38, 35, 61, 56, #FFE1, #FFDF
                DEFW #E0A8
                DEFB #0A
                DEFW 23, 31, 37, 50, #FFF2, #FFE0
                DEFW #E374
                DEFB #0A
                DEFW 25, 31, 40, 50, #FFF0, #FFE0
                DEFW #E67C
                DEFB #0A
                DEFW 26, 31, 42, 50, #FFEF, #FFE0
                DEFW #E9A4
                DEFB #0A
                DEFW 39, 31, 63, 50, #FFE2, #FFE0
                DEFW #EE60
                DEFB #0A
                DEFW 39, 31, 63, 50, #FFE2, #FFE0
                DEFW #F31C
                DEFB #0A
                DEFW 39, 31, 63, 50, #FFE2, #FFE0
                DEFW #F7D8
                DEFB #0A
                DEFW 39, 22, 63, 36, #FFE4, #FFEC
                DEFW #FB34
                DEFB #0A
                DEFW 44, 34, 71, 55, #FFE3, #FFDE
                DEFW #010C
                DEFB #0B
                DEFW 44, 34, 71, 55, #FFE3, #FFDE
                DEFW #06E4
                DEFB #0B
                DEFW 44, 34, 71, 55, #FFE3, #FFDE
                DEFW #0CBC
                DEFB #0B
                DEFW 48, 31, 77, 50, #FFE3, #FFDF
                DEFW #128C
                DEFB #0B
                DEFW 51, 30, 82, 48, #FFE3, #FFE2
                DEFW #1888
                DEFB #0B
                DEFW 47, 27, 76, 44, #FFE8, #FFE4
                DEFW #1D80
                DEFB #0B
                DEFW 47, 30, 76, 48, #FFDD, #FFE4
                DEFW #2304
                DEFB #0B
                DEFW 49, 36, 79, 58, #FFDE, #FFDE
                DEFW #29E8
                DEFB #0B
                DEFW 50, 36, 80, 58, #FFDE, #FFDE
                DEFW #30F0
                DEFB #0B
                DEFW 49, 36, 79, 58, #FFDE, #FFDE
                DEFW #37D4
                DEFB #0B
                DEFW 52, 36, 84, 58, #FFDC, #FFDE
                DEFW #3F24
                DEFB #0B
                DEFW 55, 37, 88, 60, #FFDA, #FFDD
                DEFW #4718
                DEFB #0B
                DEFW 57, 37, 92, 60, #FFDB, #FFDD
                DEFW #4F58
                DEFB #0B
                DEFW 48, 33, 77, 53, #FFDF, #FFE1
                DEFW #5588
                DEFB #0B
                DEFW 41, 31, 66, 50, #FFDE, #FFE1
                DEFW #5A80
                DEFB #0B
                DEFW 40, 31, 64, 50, #FFDE, #FFE1
                DEFW #5F58
                DEFB #0B
                DEFW 39, 31, 63, 50, #FFDE, #FFE1
                DEFW #6414
                DEFB #0B
                DEFW 39, 29, 63, 47, #FFE0, #FFE2
                DEFW #6880
                DEFB #0B
                DEFW 20, 29, 32, 47, #FFF4, #FFE2
                DEFW #6AC4
                DEFB #0B
                DEFW 39, 29, 63, 47, #FFE0, #FFE2
                DEFW #6F30
                DEFB #0B
                DEFW 24, 35, 39, 56, #FFF2, #FFDF
                DEFW #7278
                DEFB #0B
                DEFW 1, 1, 2, 2, #0000, #0000
                DEFW #727C
                DEFB #0B
                DEFW 1, 1, 2, 2, #0000, #0000
                DEFW #7280
                DEFB #0B
                DEFW 1, 1, 2, 2, #0000, #0000
                DEFW #7284
                DEFB #0B
                DEFW 1, 1, 2, 2, #0000, #0000
                DEFW #7288
                DEFB #0B
                DEFW 1, 1, 2, 2, #0000, #0000
                DEFW #728C
                DEFB #0B
                DEFW 1, 1, 2, 2, #0000, #0000
                DEFW #7290
                DEFB #0B
                DEFW 48, 33, 77, 53, #FFDF, #FFE1
                DEFW #78C0
                DEFB #0B
                DEFW 41, 31, 66, 50, #FFDE, #FFE1
                DEFW #7DB8
                DEFB #0B
                DEFW 40, 31, 64, 50, #FFDE, #FFE1
                DEFW #8290
                DEFB #0B
                DEFW 39, 31, 63, 50, #FFDE, #FFE1
                DEFW #874C
                DEFB #0B
                DEFW 39, 29, 63, 47, #FFE0, #FFE2
                DEFW #8BB8
                DEFB #0B
                DEFW 20, 29, 32, 47, #FFF4, #FFE2
                DEFW #8DFC
                DEFB #0B
                DEFW 39, 29, 63, 47, #FFE0, #FFE2
                DEFW #9268
                DEFB #0B
                DEFW 39, 32, 63, 52, #FFDF, #FFE2
                DEFW #9748
                DEFB #0B
                DEFW 38, 32, 61, 52, #FFE0, #FFDF
                DEFW #9C08
                DEFB #0B
                DEFW 40, 35, 64, 56, #FFDE, #FFDE
                DEFW #A180
                DEFB #0B
                DEFW 41, 35, 66, 56, #FFDD, #FFDE
                DEFW #A71C
                DEFB #0B
                DEFW 38, 32, 61, 52, #FFE0, #FFDF
                DEFW #ABDC
                DEFB #0B
                DEFW 41, 35, 66, 56, #FFDE, #FFDE
                DEFW #B178
                DEFB #0B
                DEFW 42, 35, 68, 56, #FFDE, #FFDE
                DEFW #B738
                DEFB #0B
                DEFW 45, 39, 72, 63, #FFDB, #FFDB
                DEFW #BE14
                DEFB #0B
                DEFW 42, 29, 68, 47, #FFDE, #FFDB
                DEFW #C2D8
                DEFB #0B
                DEFW 46, 29, 74, 47, #FFDA, #FFDB
                DEFW #C810
                DEFB #0B
                DEFW 46, 29, 74, 47, #FFDA, #FFDB
                DEFW #CD48
                DEFB #0B
                DEFW 42, 31, 68, 50, #FFDE, #FFDB
                DEFW #D260
                DEFB #0B
                DEFW 42, 31, 68, 50, #FFDE, #FFDB
                DEFW #D778
                DEFB #0B
                DEFW 42, 29, 68, 47, #FFDE, #FFDB
                DEFW #DC3C
                DEFB #0B
                DEFW 49, 25, 79, 40, #FFE0, #FFE9
                DEFW #E108
                DEFB #0B
                DEFW 60, 36, 96, 58, #FFD5, #FFDE
                DEFW #E978
                DEFB #0B
                DEFW 59, 35, 95, 56, #FFD7, #FFDF
                DEFW #F18C
                DEFB #0B
                DEFW 54, 31, 87, 50, #FFDC, #FFE2
                DEFW #F818
                DEFB #0B
                DEFW 57, 35, 92, 56, #FFD8, #FFDF
                DEFW #FFE4
                DEFB #0B
                DEFW 53, 33, 85, 53, #FFDC, #FFE1
                DEFW #06BC
                DEFB #0C
                DEFW 53, 32, 85, 52, #FFDC, #FFE2
                DEFW #0D5C
                DEFB #0C
                DEFW 52, 38, 84, 61, #FFDB, #FFDC
                DEFW #1514
                DEFB #0C
                DEFW 50, 37, 80, 60, #FFDE, #FFDC
                DEFW #1C50
                DEFB #0C
                DEFW 50, 37, 80, 60, #FFDE, #FFDC
                DEFW #238C
                DEFB #0C
                DEFW 50, 37, 80, 60, #FFDE, #FFDC
                DEFW #2AC8
                DEFB #0C
                DEFW 48, 38, 77, 61, #FFE0, #FFDC
                DEFW #31E8
                DEFB #0C
                DEFW 50, 38, 80, 61, #FFDE, #FFDC
                DEFW #3954
                DEFB #0C
                DEFW 49, 37, 79, 60, #FFE0, #FFDC
                DEFW #406C
                DEFB #0C
                DEFW 53, 37, 85, 60, #FFDC, #FFDD
                DEFW #4818
                DEFB #0C
                DEFW 52, 37, 84, 60, #FFDD, #FFDC
                DEFW #4F9C
                DEFB #0C
                DEFW 52, 37, 84, 60, #FFDD, #FFDC
                DEFW #5720
                DEFB #0C
                DEFW 52, 37, 84, 60, #FFDD, #FFDC
                DEFW #5EA4
                DEFB #0C
                DEFW 52, 37, 84, 60, #FFDD, #FFDC
                DEFW #6628
                DEFB #0C
                DEFW 51, 38, 82, 61, #FFDE, #FFDB
                DEFW #6DBC
                DEFB #0C
                DEFW 52, 37, 84, 60, #FFDD, #FFDC
                DEFW #7540
                DEFB #0C
                DEFW 53, 37, 85, 60, #FFDC, #FFDD
                DEFW #7CEC
                DEFB #0C
                DEFW 52, 37, 84, 60, #FFDD, #FFDC
                DEFW #8470
                DEFB #0C
                DEFW 52, 37, 84, 60, #FFDD, #FFDC
                DEFW #8BF4
                DEFB #0C
                DEFW 52, 37, 84, 60, #FFDD, #FFDC
                DEFW #9378
                DEFB #0C
                DEFW 52, 37, 84, 60, #FFDD, #FFDC
                DEFW #9AFC
                DEFB #0C
                DEFW 51, 38, 82, 61, #FFDE, #FFDB
                DEFW #A290
                DEFB #0C
                DEFW 52, 37, 84, 60, #FFDD, #FFDC
                DEFW #AA14
                DEFB #0C
                DEFW 45, 39, 72, 63, #FFDB, #FFDB
                DEFW #B0F0
                DEFB #0C
                DEFW 42, 29, 68, 47, #FFDE, #FFDB
                DEFW #B5B4
                DEFB #0C
                DEFW 46, 29, 74, 47, #FFDA, #FFDB
                DEFW #BAEC
                DEFB #0C
                DEFW 46, 29, 74, 47, #FFDA, #FFDB
                DEFW #C024
                DEFB #0C
                DEFW 42, 31, 68, 50, #FFDE, #FFDB
                DEFW #C53C
                DEFB #0C
                DEFW 42, 31, 68, 50, #FFDE, #FFDB
                DEFW #CA54
                DEFB #0C
                DEFW 42, 29, 68, 47, #FFDE, #FFDB
                DEFW #CF18
                DEFB #0C
                DEFW 53, 37, 85, 60, #FFDC, #FFDD
                DEFW #D6C4
                DEFB #0C
                DEFW 52, 37, 84, 60, #FFDD, #FFDC
                DEFW #DE48
                DEFB #0C
                DEFW 52, 37, 84, 60, #FFDD, #FFDC
                DEFW #E5CC
                DEFB #0C
                DEFW 52, 37, 84, 60, #FFDD, #FFDC
                DEFW #ED50
                DEFB #0C
                DEFW 52, 37, 84, 60, #FFDD, #FFDC
                DEFW #F4D4
                DEFB #0C
                DEFW 51, 38, 82, 61, #FFDE, #FFDB
                DEFW #FC68
                DEFB #0C
                DEFW 52, 37, 84, 60, #FFDD, #FFDC

HsGlyphTable:
                DEFW #0000
                DEFB #00
                DEFW #0000
                DEFB #00
                DEFB 1, 1, 1, 1, 4, 0
                DEFW #03EC
                DEFB #0D
                DEFW #04A0
                DEFB #0D
                DEFB 9, 20, 9, 20, 8, 0
                DEFW #0554
                DEFB #0D
                DEFW #063C
                DEFB #0D
                DEFB 11, 21, 11, 21, 10, 0
                DEFW #0724
                DEFB #0D
                DEFW #088C
                DEFB #0D
                DEFB 18, 20, 18, 20, 17, 0
                DEFW #09F4
                DEFB #0D
                DEFW #0B54
                DEFB #0D
                DEFB 14, 25, 14, 25, 13, 0
                DEFW #0CB4
                DEFB #0D
                DEFW #0E80
                DEFB #0D
                DEFB 23, 20, 23, 20, 22, 0
                DEFW #104C
                DEFB #0D
                DEFW #11B4
                DEFB #0D
                DEFB 18, 20, 18, 20, 17, 0
                DEFW #131C
                DEFB #0D
                DEFW #13B0
                DEFB #0D
                DEFB 7, 21, 7, 21, 6, 0
                DEFW #1444
                DEFB #0D
                DEFW #1540
                DEFB #0D
                DEFB 10, 25, 10, 25, 9, 0
                DEFW #163C
                DEFB #0D
                DEFW #1738
                DEFB #0D
                DEFB 10, 25, 10, 25, 9, 0
                DEFW #1834
                DEFB #0D
                DEFW #195C
                DEFB #0D
                DEFB 14, 21, 14, 21, 13, 0
                DEFW #1A84
                DEFB #0D
                DEFW #1BB8
                DEFB #0D
                DEFB 18, 17, 18, 17, 17, 0
                DEFW #1CEC
                DEFB #0D
                DEFW #1D50
                DEFB #0D
                DEFB 9, 11, 9, 11, 8, 0
                DEFW #1DB4
                DEFB #0D
                DEFW #1E2C
                DEFB #0D
                DEFB 10, 12, 10, 12, 9, 0
                DEFW #1EA4
                DEFB #0D
                DEFW #1EE4
                DEFB #0D
                DEFB 9, 7, 9, 7, 8, 0
                DEFW #1F24
                DEFB #0D
                DEFW #202C
                DEFB #0D
                DEFB 11, 24, 11, 24, 10, 0
                DEFW #2134
                DEFB #0D
                DEFW #224C
                DEFB #0D
                DEFB 14, 20, 14, 20, 13, 0
                DEFW #2364
                DEFB #0D
                DEFW #247C
                DEFB #0D
                DEFB 14, 20, 14, 20, 13, 0
                DEFW #2594
                DEFB #0D
                DEFW #26AC
                DEFB #0D
                DEFB 14, 20, 14, 20, 13, 0
                DEFW #27C4
                DEFB #0D
                DEFW #28DC
                DEFB #0D
                DEFB 14, 20, 14, 20, 13, 0
                DEFW #29F4
                DEFB #0D
                DEFW #2B0C
                DEFB #0D
                DEFB 14, 20, 14, 20, 13, 0
                DEFW #2C24
                DEFB #0D
                DEFW #2D3C
                DEFB #0D
                DEFB 14, 20, 14, 20, 13, 0
                DEFW #2E54
                DEFB #0D
                DEFW #2F6C
                DEFB #0D
                DEFB 14, 20, 14, 20, 13, 0
                DEFW #3084
                DEFB #0D
                DEFW #319C
                DEFB #0D
                DEFB 14, 20, 14, 20, 13, 0
                DEFW #32B4
                DEFB #0D
                DEFW #33CC
                DEFB #0D
                DEFB 14, 20, 14, 20, 13, 0
                DEFW #34E4
                DEFB #0D
                DEFW #35FC
                DEFB #0D
                DEFB 14, 20, 14, 20, 13, 0
                DEFW #3714
                DEFB #0D
                DEFW #37B4
                DEFB #0D
                DEFB 10, 16, 10, 16, 9, 0
                DEFW #3854
                DEFB #0D
                DEFW #391C
                DEFB #0D
                DEFB 10, 20, 10, 20, 9, 0
                DEFW #39E4
                DEFB #0D
                DEFW #3B28
                DEFB #0D
                DEFB 18, 18, 18, 18, 17, 0
                DEFW #3C6C
                DEFB #0D
                DEFW #3D68
                DEFB #0D
                DEFB 18, 14, 18, 14, 17, 0
                DEFW #3E64
                DEFB #0D
                DEFW #3FA8
                DEFB #0D
                DEFB 18, 18, 18, 18, 17, 0
                DEFW #40EC
                DEFB #0D
                DEFW #41DC
                DEFB #0D
                DEFB 12, 20, 12, 20, 11, 0
                DEFW #42CC
                DEFB #0D
                DEFW #44B0
                DEFB #0D
                DEFB 22, 22, 22, 22, 21, 0
                DEFW #4694
                DEFB #0D
                DEFW #47E8
                DEFB #0D
                DEFB 17, 20, 17, 20, 16, 0
                DEFW #493C
                DEFB #0D
                DEFW #4A68
                DEFB #0D
                DEFB 15, 20, 15, 20, 14, 0
                DEFW #4B94
                DEFB #0D
                DEFW #4CC0
                DEFB #0D
                DEFB 15, 20, 15, 20, 14, 0
                DEFW #4DEC
                DEFB #0D
                DEFW #4F40
                DEFB #0D
                DEFB 17, 20, 17, 20, 16, 0
                DEFW #5094
                DEFB #0D
                DEFW #51AC
                DEFB #0D
                DEFB 14, 20, 14, 20, 13, 0
                DEFW #52C4
                DEFB #0D
                DEFW #53DC
                DEFB #0D
                DEFB 14, 20, 14, 20, 13, 0
                DEFW #54F4
                DEFB #0D
                DEFW #5648
                DEFB #0D
                DEFB 17, 20, 17, 20, 16, 0
                DEFW #579C
                DEFB #0D
                DEFW #58F0
                DEFB #0D
                DEFB 17, 20, 17, 20, 16, 0
                DEFW #5A44
                DEFB #0D
                DEFW #5B0C
                DEFB #0D
                DEFB 10, 20, 10, 20, 9, 0
                DEFW #5BD4
                DEFB #0D
                DEFW #5CB0
                DEFB #0D
                DEFB 11, 20, 11, 20, 10, 0
                DEFW #5D8C
                DEFB #0D
                DEFW #5ECC
                DEFB #0D
                DEFB 16, 20, 16, 20, 15, 0
                DEFW #600C
                DEFB #0D
                DEFW #6110
                DEFB #0D
                DEFB 13, 20, 13, 20, 12, 0
                DEFW #6214
                DEFB #0D
                DEFW #6390
                DEFB #0D
                DEFB 19, 20, 19, 20, 18, 0
                DEFW #650C
                DEFB #0D
                DEFW #6660
                DEFB #0D
                DEFB 17, 20, 17, 20, 16, 0
                DEFW #67B4
                DEFB #0D
                DEFW #691C
                DEFB #0D
                DEFB 18, 20, 18, 20, 17, 0
                DEFW #6A84
                DEFB #0D
                DEFW #6B9C
                DEFB #0D
                DEFB 14, 20, 14, 20, 13, 0
                DEFW #6CB4
                DEFB #0D
                DEFW #6E64
                DEFB #0D
                DEFB 18, 24, 18, 24, 17, 0
                DEFW #7014
                DEFB #0D
                DEFW #7168
                DEFB #0D
                DEFB 17, 20, 17, 20, 16, 0
                DEFW #72BC
                DEFB #0D
                DEFW #73D4
                DEFB #0D
                DEFB 14, 20, 14, 20, 13, 0
                DEFW #74EC
                DEFB #0D
                DEFW #762C
                DEFB #0D
                DEFB 16, 20, 16, 20, 15, 0
                DEFW #776C
                DEFB #0D
                DEFW #78AC
                DEFB #0D
                DEFB 16, 20, 16, 20, 15, 0
                DEFW #79EC
                DEFB #0D
                DEFW #7B40
                DEFB #0D
                DEFB 17, 20, 17, 20, 16, 0
                DEFW #7C94
                DEFB #0D
                DEFW #7E4C
                DEFB #0D
                DEFB 22, 20, 22, 20, 21, 0
                DEFW #8004
                DEFB #0D
                DEFW #8130
                DEFB #0D
                DEFB 15, 20, 15, 20, 14, 0
                DEFW #825C
                DEFB #0D
                DEFW #839C
                DEFB #0D
                DEFB 16, 20, 16, 20, 15, 0
                DEFW #84DC
                DEFB #0D
                DEFW #85F4
                DEFB #0D
                DEFB 14, 20, 14, 20, 13, 0
                DEFW #870C
                DEFB #0D
                DEFW #8808
                DEFB #0D
                DEFB 10, 25, 10, 25, 9, 0
                DEFW #8904
                DEFB #0D
                DEFW #8A0C
                DEFB #0D
                DEFB 11, 24, 11, 24, 10, 0
                DEFW #8B14
                DEFB #0D
                DEFW #8C10
                DEFB #0D
                DEFB 10, 25, 10, 25, 9, 0
                DEFW #8D0C
                DEFB #0D
                DEFW #8E74
                DEFB #0D
                DEFB 18, 20, 18, 20, 17, 0
                DEFW #8FDC
                DEFB #0D
                DEFW #905C
                DEFB #0D
                DEFB 16, 8, 16, 8, 15, 0
                DEFW #90DC
                DEFB #0D
                DEFW #9210
                DEFB #0D
                DEFB 14, 22, 14, 22, 13, 0
                DEFW #9344
                DEFB #0D
                DEFW #9424
                DEFB #0D
                DEFB 14, 16, 14, 16, 13, 0
                DEFW #9504
                DEFB #0D
                DEFW #962C
                DEFB #0D
                DEFB 14, 21, 14, 21, 13, 0
                DEFW #9754
                DEFB #0D
                DEFW #9814
                DEFB #0D
                DEFB 12, 16, 12, 16, 11, 0
                DEFW #98D4
                DEFB #0D
                DEFW #99FC
                DEFB #0D
                DEFB 14, 21, 14, 21, 13, 0
                DEFW #9B24
                DEFB #0D
                DEFW #9C04
                DEFB #0D
                DEFB 14, 16, 14, 16, 13, 0
                DEFW #9CE4
                DEFB #0D
                DEFW #9DB8
                DEFB #0D
                DEFB 10, 21, 10, 21, 9, 0
                DEFW #9E8C
                DEFB #0D
                DEFW #9FA4
                DEFB #0D
                DEFB 14, 20, 14, 20, 13, 0
                DEFW #A0BC
                DEFB #0D
                DEFW #A1E4
                DEFB #0D
                DEFB 14, 21, 14, 21, 13, 0
                DEFW #A30C
                DEFB #0D
                DEFW #A398
                DEFB #0D
                DEFB 7, 20, 7, 20, 6, 0
                DEFW #A424
                DEFB #0D
                DEFW #A4FC
                DEFB #0D
                DEFB 9, 24, 9, 24, 8, 0
                DEFW #A5D4
                DEFB #0D
                DEFW #A6FC
                DEFB #0D
                DEFB 14, 21, 14, 21, 13, 0
                DEFW #A824
                DEFB #0D
                DEFW #A8B8
                DEFB #0D
                DEFB 7, 21, 7, 21, 6, 0
                DEFW #A94C
                DEFB #0D
                DEFW #AA8C
                DEFB #0D
                DEFB 20, 16, 20, 16, 19, 0
                DEFW #ABCC
                DEFB #0D
                DEFW #ACAC
                DEFB #0D
                DEFB 14, 16, 14, 16, 13, 0
                DEFW #AD8C
                DEFB #0D
                DEFW #AE6C
                DEFB #0D
                DEFB 14, 16, 14, 16, 13, 0
                DEFW #AF4C
                DEFB #0D
                DEFW #B064
                DEFB #0D
                DEFB 14, 20, 14, 20, 13, 0
                DEFW #B17C
                DEFB #0D
                DEFW #B294
                DEFB #0D
                DEFB 14, 20, 14, 20, 13, 0
                DEFW #B3AC
                DEFB #0D
                DEFW #B44C
                DEFB #0D
                DEFB 10, 16, 10, 16, 9, 0
                DEFW #B4EC
                DEFB #0D
                DEFW #B5AC
                DEFB #0D
                DEFB 12, 16, 12, 16, 11, 0
                DEFW #B66C
                DEFB #0D
                DEFW #B72C
                DEFB #0D
                DEFB 10, 19, 10, 19, 9, 0
                DEFW #B7EC
                DEFB #0D
                DEFW #B8CC
                DEFB #0D
                DEFB 14, 16, 14, 16, 13, 0
                DEFW #B9AC
                DEFB #0D
                DEFW #BA7C
                DEFB #0D
                DEFB 13, 16, 13, 16, 12, 0
                DEFW #BB4C
                DEFB #0D
                DEFW #BC6C
                DEFB #0D
                DEFB 18, 16, 18, 16, 17, 0
                DEFW #BD8C
                DEFB #0D
                DEFW #BE5C
                DEFB #0D
                DEFB 13, 16, 13, 16, 12, 0
                DEFW #BF2C
                DEFB #0D
                DEFW #C030
                DEFB #0D
                DEFB 13, 20, 13, 20, 12, 0
                DEFW #C134
                DEFB #0D
                DEFW #C1F4
                DEFB #0D
                DEFB 12, 16, 12, 16, 11, 0
                DEFW #C2B4
                DEFB #0D
                DEFW #C3FC
                DEFB #0D
                DEFB 13, 25, 13, 25, 12, 0
                DEFW #C544
                DEFB #0D
                DEFW #C640
                DEFB #0D
                DEFB 10, 25, 10, 25, 9, 0
                DEFW #C73C
                DEFB #0D
                DEFW #C884
                DEFB #0D
                DEFB 13, 25, 13, 25, 12, 0
                DEFW #C9CC
                DEFB #0D
                DEFW #CAC8
                DEFB #0D
                DEFB 18, 14, 18, 14, 17, 0

HsStandardPlayer0: DEFB "Lord Kilburn", 0
HsStandardScenario0: DEFB "Beltway", 0
HsStandardPlayer1: DEFB "Tsabu", 0
HsStandardScenario1: DEFB "Deathgate", 0
HsStandardPlayer2: DEFB "Sir Galant", 0
HsStandardScenario2: DEFB "Enroth", 0
HsStandardPlayer3: DEFB "Thundax", 0
HsStandardScenario3: DEFB "Lost Continent", 0
HsStandardPlayer4: DEFB "Lord Haart", 0
HsStandardScenario4: DEFB "Mountain King", 0
HsStandardPlayer5: DEFB "Ariel", 0
HsStandardScenario5: DEFB "Pandemonium", 0
HsStandardPlayer6: DEFB "Rebecca", 0
HsStandardScenario6: DEFB "Terra Firma", 0
HsStandardPlayer7: DEFB "Sandro", 0
HsStandardScenario7: DEFB "The Clearing", 0
HsStandardPlayer8: DEFB "Crodo", 0
HsStandardScenario8: DEFB "Vikings!", 0
HsStandardPlayer9: DEFB "Barock", 0
HsStandardScenario9: DEFB "Wastelands", 0
HsStandardRows:
                DEFW HsStandardPlayer0, HsStandardScenario0, 70, 150, HsMonsterTable + 4095, HsMonsterTable + 4110
                DEFW HsStandardPlayer1, HsStandardScenario1, 80, 140, HsMonsterTable + 3675, HsMonsterTable + 3690
                DEFW HsStandardPlayer2, HsStandardScenario2, 90, 130, HsMonsterTable + 3360, HsMonsterTable + 3375
                DEFW HsStandardPlayer3, HsStandardScenario3, 100, 120, HsMonsterTable + 3150, HsMonsterTable + 3165
                DEFW HsStandardPlayer4, HsStandardScenario4, 120, 110, HsMonsterTable + 2835, HsMonsterTable + 2850
                DEFW HsStandardPlayer5, HsStandardScenario5, 140, 100, HsMonsterTable + 2625, HsMonsterTable + 2640
                DEFW HsStandardPlayer6, HsStandardScenario6, 160, 90, HsMonsterTable + 2310, HsMonsterTable + 2325
                DEFW HsStandardPlayer7, HsStandardScenario7, 180, 80, HsMonsterTable + 2100, HsMonsterTable + 2115
                DEFW HsStandardPlayer8, HsStandardScenario8, 200, 70, HsMonsterTable + 1785, HsMonsterTable + 1800
                DEFW HsStandardPlayer9, HsStandardScenario9, 240, 60, HsMonsterTable + 1575, HsMonsterTable + 1590

HsCampaignPlayer0: DEFB "Antoine", 0
HsCampaignScenario0: DEFB "Roland", 0
HsCampaignPlayer1: DEFB "Astra", 0
HsCampaignScenario1: DEFB "Archibald", 0
HsCampaignPlayer2: DEFB "Agar", 0
HsCampaignScenario2: DEFB "Roland", 0
HsCampaignPlayer3: DEFB "Vatawna", 0
HsCampaignScenario3: DEFB "Archibald", 0
HsCampaignPlayer4: DEFB "Vesper", 0
HsCampaignScenario4: DEFB "Roland", 0
HsCampaignPlayer5: DEFB "Ambrose", 0
HsCampaignScenario5: DEFB "Archibald", 0
HsCampaignPlayer6: DEFB "Troyan", 0
HsCampaignScenario6: DEFB "Roland", 0
HsCampaignPlayer7: DEFB "Jojosh", 0
HsCampaignScenario7: DEFB "Archibald", 0
HsCampaignPlayer8: DEFB "Wrathmont", 0
HsCampaignScenario8: DEFB "Roland", 0
HsCampaignPlayer9: DEFB "Maximus", 0
HsCampaignScenario9: DEFB "Archibald", 0
HsCampaignRows:
                DEFW HsCampaignPlayer0, HsCampaignScenario0, 600, 600, HsMonsterTable + 5250, HsMonsterTable + 5265
                DEFW HsCampaignPlayer1, HsCampaignScenario1, 650, 650, HsMonsterTable + 4935, HsMonsterTable + 4950
                DEFW HsCampaignPlayer2, HsCampaignScenario2, 700, 700, HsMonsterTable + 4725, HsMonsterTable + 4740
                DEFW HsCampaignPlayer3, HsCampaignScenario3, 750, 750, HsMonsterTable + 4410, HsMonsterTable + 4425
                DEFW HsCampaignPlayer4, HsCampaignScenario4, 800, 800, HsMonsterTable + 4200, HsMonsterTable + 4215
                DEFW HsCampaignPlayer5, HsCampaignScenario5, 850, 850, HsMonsterTable + 3885, HsMonsterTable + 3900
                DEFW HsCampaignPlayer6, HsCampaignScenario6, 900, 900, HsMonsterTable + 3675, HsMonsterTable + 3690
                DEFW HsCampaignPlayer7, HsCampaignScenario7, 1000, 1000, HsMonsterTable + 3150, HsMonsterTable + 3165
                DEFW HsCampaignPlayer8, HsCampaignScenario8, 2000, 2000, HsMonsterTable + 2100, HsMonsterTable + 2115
                DEFW HsCampaignPlayer9, HsCampaignScenario9, 3000, 3000, HsMonsterTable + 1575, HsMonsterTable + 1590

                endif