; Сгенерировано Source/Tools/viewport_pack.py — PickupList в #91 (вынос из резидента).
PickupList:
                DEFB 19, 6, 3
                DEFB 20, 6, 3
                DEFB 23, 7, 0
                DEFB 17, 9, 1
                DEFB 27, 9, 0
                DEFB 12, 10, 1
                DEFB 33, 10, 5
                DEFB 10, 13, 3
                DEFB 19, 13, 2
                DEFB 10, 14, 3
                DEFB 11, 19, 4
                DEFB 4, 21, 6
                DEFB 15, 22, 2
                DEFB 24, 22, 4
                DEFB 27, 22, 6
                DEFB 20, 23, 4
                DEFB 17, 26, 5
                DEFB 18, 26, 5
                DEFB 15, 29, 0
                DEFB 14, 32, 0
